### ISSUE TITLE
SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by tharik15** [razaghimahdi/Shopping-By-KMP#12]
**Not able to register credential, Below exception is happen when clicking Sign Up.**

AppDebug KtorHttpClient message:REQUEST https://shop.soheilkhaledabadi.ir/api/v1/register failed with exception: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-09-16 09:59:37.803 19465-19465 System.err                                         W  javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-09-16 09:59:37.804 19465-19465 System.err                                         W  	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
2024-09-16 09:59:37.804 19465-19465 System.err                                         W  	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
2024-09-16 09:59:37.804 19465-19465 System.err                                         W  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
2024-09-16 09:59:37.804 19465-19465 System.err                                         W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
2024-09-16 09:59:37.804 19465-19465 System.err                                         W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2024-09-16 09:59:37.804 19465-19465 System.err                                         W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)

**Comment by tharik15** [comment]
Is there any update?

**Comment by razaghimahdi** [comment]
it's actually been fixed, it was from backend and now it works fine, thanks for opening an issue
